### ISSUE TITLE
Go!, Python or PHP?

### ISSUE THREAD

**Issue by kanafghan** [kanafghan/fiziq-backend#1]
What should we choose as the backend language for writing the Backend for Fiziq?

Both Go! and PHP for Google App Engine are in Beta now. Only Python and Java are stable in the moment. I have experience with developing using Python.

What do you say?

**Comment by toin0u** [comment]
I'll say Python because it's stable :) But why not Go ? What do you think @khannoori ?

**Comment by kanafghan** [comment]
You ask why not Go!? Here is an explanation: http://stackoverflow.com/questions/6166660/google-app-engine-go-vs-python-recommendations

and I agree with it. Google tend to change a lot, especially when stuff are beta or in experimental state.

**Comment by toin0u** [comment]
Let's go for Python then :dancer:

**Comment by kanafghan** [comment]
Since the choice is Python, I clone this issue.

**Comment by khannoori** [comment]
Sorry for the late answer, well i am also on the same side as you guys.
Happy Coding:-)
